apiVersion: v1
kind: Service
metadata:
  name: devbakkie-service
spec:
  type: NodePort
  selector:
    app: devbakkie
  ports:
  - protocol: TCP
    nodePort: 30300
    port: 4444
    targetPort: 4444